const DEMO_PROFILES = [
  {
    name: 'Jordan Mitchell',
    role: 'Product Designer · Independent',
    bio: 'Designing thoughtful digital experiences at the intersection of craft and purpose. Previously at Figma, currently building protome.',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    links: [
      { label: 'Portfolio', url: '#' },
      { label: 'Case Studies', url: '#' },
      { label: 'LinkedIn', url: '#' },
      { label: 'GitHub', url: '#' },
      { label: 'Twitter', url: '#' },
      { label: 'Reddit', url: '#' },
    ],
    accent: '#c45a3c',
    bgColor: '#1c1a19',
    bgGradient: '__gooey__',
    bgType: 'pattern',
    bg_size: '400px 400px',
    font: '',
    button_style: 'outline',
    button_corner: 'pill',
  },
  {
    name: 'Alex Chen',
    role: 'Full-Stack Developer · Open Source',
    bio: 'Building tools for the next million developers. Core contributor to Astro and Vite. Love CLI tools, design systems, and good documentation.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    links: [
      { label: 'Personal site', url: '#' },
      { label: 'Projects', url: '#' },
      { label: 'GitHub', url: '#' },
      { label: 'Twitter', url: '#' },
      { label: 'Discord', url: '#' },
    ],
    accent: '#2563eb',
    bgColor: '#e8eff5',
    bgGradient: 'linear-gradient(145deg, #f0f5fa 0%, #e0e8f2 50%, #f0f5fa 100%)',
    bgType: 'gradient',
    font: 'mono',
    button_style: 'glass',
    button_corner: 'rounded',
  },
  {
    name: 'Maya Rivera',
    role: 'Writer · Creative Director',
    bio: 'Words for brands that mean it. Previously copy lead at Mailchimp, now running my own studio. Newsletter hits 40k inboxes weekly.',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    links: [
      { label: 'Newsletter', url: '#' },
      { label: 'Latest articles', url: '#' },
      { label: 'Twitter', url: '#' },
      { label: 'Instagram', url: '#' },
      { label: 'Website', url: '#' },
    ],
    accent: '#e8a0b0',
    bgColor: '#221515',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, rgba(200,180,255,0.25) 0%, transparent 70%)',
    bgType: 'glow',
    font: 'hand',
    button_style: 'glass',
    button_corner: 'square',
  },
  {
    name: 'Sam Okafor',
    role: 'Indie Maker · No-code',
    bio: 'Shipping SaaS products without writing a line of code. Built 3 profitable tools in 12 months. I teach no-code at buildinpublic.co.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    links: [
      { label: 'My tools', url: '#' },
      { label: 'Free templates', url: '#' },
      { label: 'YouTube', url: '#' },
      { label: 'Twitter', url: '#' },
      { label: 'TikTok', url: '#' },
    ],
    accent: '#059669',
    bgColor: '#f7efe5',
    bgGradient: 'linear-gradient(145deg, #fefaf5 0%, #f5ede3 50%, #fefaf5 100%)',
    font: 'bold',
    button_style: 'solid',
    button_corner: 'rounded',
  },
]

const DEFAULT_DATA = DEMO_PROFILES[0]

const LINK_LABELS = {
  website: 'Website',
  linkedin: 'LinkedIn',
  twitter: 'X / Twitter',
  github: 'GitHub',
  instagram: 'Instagram',
  youtube: 'YouTube',
  tiktok: 'TikTok',
  facebook: 'Facebook',
  snapchat: 'Snapchat',
  discord: 'Discord',
  twitch: 'Twitch',
  pinterest: 'Pinterest',
  reddit: 'Reddit',
  telegram: 'Telegram',
  whatsapp: 'WhatsApp',
  threads: 'Threads',
  bluesky: 'Bluesky',
}

export { DEMO_PROFILES, DEFAULT_DATA, LINK_LABELS }
