/**
 * Post-build script: reads dist/index.html and generates api/_html.js
 * for the Vercel Edge Function, so it doesn't need fs access at runtime.
 *
 * Run automatically after `vite build` via the `build` script in package.json.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const distIndex = join(root, "dist", "index.html");
const outFile = join(root, "api", "_html.js");

if (!existsSync(distIndex)) {
  console.error("  ✗ dist/index.html not found — run `vite build` first.");
  process.exit(1);
}

const html = readFileSync(distIndex, "utf-8");

writeFileSync(
  outFile,
  `// Auto-generated by scripts/build-html.js — do not edit
// To rebuild: npm run build
const HTML = ${JSON.stringify(html)};
export { HTML };
`,
  "utf-8",
);

console.log(`  ✓ Inlined dist/index.html into api/_html.js (${html.length} bytes)`);
